export const DEFAULT_FONT_SIZE = 14;

export const MACOS_FONTS = [
  "\"Academy Engraved LET\"",
  "\"Adelle Sans Devanagari\"",
  "AkayaKanadaka",
  "AkayaTelivigala",
  "\"Al Bayan\"",
  "\"Al Nile\"",
  "\"Al Tarikh\"",
  "\"American Typewriter\"",
  "\"Andale Mono\"",
  "\"Annai MN\"",
  "\"Apple Braille\"",
  "\"Apple Chancery\"",
  "\"Apple Color Emoji\"",
  "\"Apple LiGothic\"",
  "\"Apple LiSung\"",
  "\"Apple SD Gothic Neo\"",
  "\"Apple Symbols\"",
  "AppleGothic",
  "AppleMyungjo",
  "Arial",
  "\"Arial Black\"",
  "\"Arial Hebrew Scholar\"",
  "\"Arial Hebrew\"",
  "\"Arial Narrow\"",
  "\"Arial Rounded MT Bold\"",
  "\"Arial Unicode MS\"",
  "\"Arima Koshi\"",
  "\"Arima Madurai\"",
  "Avenir",
  "\"Avenir Next Condensed\"",
  "\"Avenir Next\"",
  "Ayuthaya",
  "Baghdad",
  "\"Bai Jamjuree\"",
  "\"Baloo 2\"",
  "\"Baloo Bhai 2\"",
  "\"Baloo Bhaijaan\"",
  "\"Baloo Bhaina 2\"",
  "\"Baloo Chettan 2\"",
  "\"Baloo Da 2\"",
  "\"Baloo Paaji 2\"",
  "\"Baloo Tamma 2\"",
  "\"Baloo Tammudu 2\"",
  "\"Baloo Thambi 2\"",
  "\"Bangla MN\"",
  "\"Bangla Sangam MN\"",
  "\"Baoli SC\"",
  "\"Baoli TC\"",
  "Baskerville",
  "Beirut",
  "BiauKaiHK",
  "BiauKaiTC",
  "\"Big Caslon\"",
  "\"BM Dohyeon\"",
  "\"BM Hanna 11yrs Old\"",
  "\"BM Hanna Air\"",
  "\"BM Hanna Pro\"",
  "\"BM Jua\"",
  "\"BM Kirang Haerang\"",
  "\"BM Yeonsung\"",
  "\"Bodoni 72 Oldstyle\"",
  "\"Bodoni 72 Smallcaps\"",
  "\"Bodoni 72\"",
  "\"Bodoni Ornaments\"",
  "\"Bradley Hand\"",
  "\"Brush Script MT\"",
  "\"Cambay Devanagari\"",
  "\"Chakra Petch\"",
  "Chalkboard",
  "\"Chalkboard SE\"",
  "Chalkduster",
  "Charm",
  "Charmonman",
  "Charter",
  "Cochin",
  "\"Comic Sans MS\"",
  "Copperplate",
  "\"Corsiva Hebrew\"",
  "\"Courier New\"",
  "Damascus",
  "\"DecoType Naskh\"",
  "\"Devanagari MT\"",
  "\"Devanagari Sangam MN\"",
  "Didot",
  "\"DIN Alternate\"",
  "\"DIN Condensed\"",
  "\"Diwan Kufi\"",
  "\"Diwan Thuluth\"",
  "\"Euphemia UCAS\"",
  "Fahkwang",
  "Farah",
  "Farisi",
  "Futura",
  "Galvji",
  "\"GB18030 Bitmap\"",
  "\"Geeza Pro\"",
  "Geneva",
  "Georgia",
  "\"Gill Sans\"",
  "Gotu",
  "\"Grantha Sangam MN\"",
  "\"Gujarati MT\"",
  "\"Gujarati Sangam MN\"",
  "GungSeo",
  "\"Gurmukhi MN\"",
  "\"Gurmukhi MT\"",
  "\"Gurmukhi Sangam MN\"",
  "\"Hannotate SC\"",
  "\"Hannotate TC\"",
  "\"HanziPen SC\"",
  "\"HanziPen TC\"",
  "HeadLineA",
  "Hei",
  "\"Heiti SC\"",
  "\"Heiti TC\"",
  "Helvetica",
  "\"Helvetica Neue\"",
  "Herculanum",
  "\"Hiragino Maru Gothic ProN\"",
  "\"Hiragino Mincho ProN\"",
  "\"Hiragino Sans CNS\"",
  "\"Hiragino Sans GB\"",
  "\"Hiragino Sans\"",
  "\"Hoefler Text\"",
  "Hubballi",
  "Impact",
  "InaiMathi",
  "\"ITF Devanagari Marathi\"",
  "\"ITF Devanagari\"",
  "Jaini",
  "\"Jaini Purva\"",
  "K2D",
  "Kai",
  "Kailasa",
  "\"Kaiti SC\"",
  "\"Kaiti TC\"",
  "\"Kannada MN\"",
  "\"Kannada Sangam MN\"",
  "Katari",
  "Kavivanar",
  "Kefa",
  "\"Khmer MN\"",
  "\"Khmer Sangam MN\"",
  "Klee",
  "Kodchasan",
  "\"Kohinoor Bangla\"",
  "\"Kohinoor Devanagari\"",
  "\"Kohinoor Gujarati\"",
  "\"Kohinoor Telugu\"",
  "KoHo",
  "Kokonor",
  "Krub",
  "Krungthep",
  "KufiStandardGK",
  "\"Lahore Gurmukhi\"",
  "\"Lantinghei SC\"",
  "\"Lantinghei TC\"",
  "\"Lao MN\"",
  "\"Lao Sangam MN\"",
  "\"Lava Devanagari\"",
  "\"Lava Kannada\"",
  "\"Lava Telugu\"",
  "\"Libian SC\"",
  "\"Libian TC\"",
  "\"LiHei Pro\"",
  "\"LingWai SC\"",
  "\"LingWai TC\"",
  "\"LiSong Pro\"",
  "\"Lucida Grande\"",
  "Luminari",
  "Maku",
  "\"Malayalam MN\"",
  "\"Malayalam Sangam MN\"",
  "Mali",
  "\"Marker Felt\"",
  "Menlo",
  "\"Microsoft Sans Serif\"",
  "Mishafi",
  "\"Mishafi Gold\"",
  "Modak",
  "Monaco",
  "Mshtakan",
  "Mukta",
  "\"Mukta Mahee\"",
  "\"Mukta Malar\"",
  "\"Mukta Vaani\"",
  "Muna",
  "\"Myanmar MN\"",
  "\"Myanmar Sangam MN\"",
  "Nadeem",
  "\"Nanum Brush Script\"",
  "\"Nanum Gothic\"",
  "\"Nanum Myeongjo\"",
  "\"Nanum Pen Script\"",
  "\"New Peninim MT\"",
  "Niramit",
  "Noteworthy",
  "\"Noto Nastaliq Urdu\"",
  "\"Noto Sans Kannada\"",
  "\"Noto Sans Myanmar\"",
  "\"Noto Sans Oriya\"",
  "\"Noto Serif Kannada\"",
  "\"Noto Serif Myanmar\"",
  "\"October Compressed Devanagari\"",
  "\"October Compressed Tamil\"",
  "\"October Condensed Devanagari\"",
  "\"October Condensed Tamil\"",
  "\"October Devanagari\"",
  "\"October Tamil\"",
  "Optima",
  "\"Oriya MN\"",
  "\"Oriya Sangam MN\"",
  "Osaka",
  "\"Padyakke Expanded One\"",
  "Palatino",
  "Papyrus",
  "\"Party LET\"",
  "PCMyungjo",
  "Phosphate",
  "PilGi",
  "\"PingFang HK\"",
  "\"PingFang SC\"",
  "\"PingFang TC\"",
  "\"Plantagenet Cherokee\"",
  "\"PSL Ornanong Pro\"",
  "\"PT Mono\"",
  "\"PT Sans Caption\"",
  "\"PT Sans Narrow\"",
  "\"PT Sans\"",
  "\"PT Serif Caption\"",
  "\"PT Serif\"",
  "Raanana",
  "Rockwell",
  "\"Sama Devanagari\"",
  "\"Sama Gujarati\"",
  "\"Sama Gurmukhi\"",
  "\"Sama Kannada\"",
  "\"Sama Malayalam\"",
  "\"Sama Tamil\"",
  "Sana",
  "Sarabun",
  "Sathu",
  "\"Savoye LET\"",
  "Shobhika",
  "\"Shree Devanagari 714\"",
  "SignPainter",
  "Silom",
  "SimSong",
  "\"Sinhala MN\"",
  "\"Sinhala Sangam MN\"",
  "Skia",
  "\"Snell Roundhand\"",
  "\"Songti SC\"",
  "\"Songti TC\"",
  "Srisakdi",
  "STFangsong",
  "STHeiti",
  "\"STIX Two Math\"",
  "\"STIX Two Text\"",
  "STKaiti",
  "STSong",
  "\"Sukhumvit Set\"",
  "Symbol",
  "Tahoma",
  "\"Tamil MN\"",
  "\"Tamil Sangam MN\"",
  "\"Telugu MN\"",
  "\"Telugu Sangam MN\"",
  "Thonburi",
  "\"Times New Roman\"",
  "\"Tiro Bangla\"",
  "\"Tiro Devanagari Hindi\"",
  "\"Tiro Devanagari Marathi\"",
  "\"Tiro Devanagari Sanskrit\"",
  "\"Tiro Gurmukhi\"",
  "\"Tiro Kannada\"",
  "\"Tiro Tamil\"",
  "\"Tiro Telugu\"",
  "\"Toppan Bunkyu Gothic\"",
  "\"Toppan Bunkyu Midashi Gothic\"",
  "\"Toppan Bunkyu Midashi Mincho\"",
  "\"Toppan Bunkyu Mincho\"",
  "Trattatello",
  "\"Trebuchet MS\"",
  "\"Tsukushi A Round Gothic\"",
  "\"Tsukushi B Round Gothic\"",
  "Verdana",
  "Waseem",
  "\"Wawati SC\"",
  "\"Wawati TC\"",
  "Webdings",
  "Wingdings",
  "\"Wingdings 2\"",
  "\"Wingdings 3\"",
  "\"Xingkai SC\"",
  "\"Xingkai TC\"",
  "\"Yuanti SC\"",
  "\"Yuanti TC\"",
  "YuGothic",
  "YuKyokasho",
  "\"YuKyokasho Yoko\"",
  "YuMincho",
  "\"YuMincho +36p Kana\"",
  "\"Yuppy SC\"",
  "\"Yuppy TC\"",
  "\"Zapf Dingbats\"",
  "Zapfino"
]

export const WINDOWS_FONTS = [
  "\"Agency FB\"",
  "Algerian",
  "Arial",
  "\"Arial Rounded MT\"",
  "\"Arial Unicode MS\"",
  "\"Axure Handwriting\"",
  "Bahnschrift",
  "\"Baskerville Old Face\"",
  "\"Bauhaus 93\"",
  "\"Bell MT\"",
  "\"Berlin Sans FB\"",
  "\"Bernard MT\"",
  "\"Blackadder ITC\"",
  "\"Bodoni MT Poster\"",
  "\"Bodoni MT\"",
  "\"Book Antiqua\"",
  "\"Bookman Old Style\"",
  "\"Bookshelf Symbol 7\"",
  "\"Bradley Hand ITC\"",
  "Britannic",
  "Broadway",
  "\"Brush Script MT\"",
  "Calibri",
  "\"Californian FB\"",
  "\"Calisto MT\"",
  "Cambria",
  "\"Cambria Math\"",
  "Candara",
  "\"Cascadia Code\"",
  "\"Cascadia Mono\"",
  "Castellar",
  "Centaur",
  "Century",
  "\"Century Gothic\"",
  "\"Century Schoolbook\"",
  "Chiller",
  "\"Colonna MT\"",
  "\"Comic Sans MS\"",
  "Consolas",
  "Constantia",
  "Cooper",
  "\"Copperplate Gothic\"",
  "Corbel",
  "\"Courier New\"",
  "\"Curlz MT\"",
  "\"DejaVu Math TeX Gyre\"",
  "Ebrima",
  "\"Edwardian Script ITC\"",
  "Elephant",
  "\"Engravers MT\"",
  "\"Eras ITC\"",
  "\"Felix Titling\"",
  "\"Footlight MT\"",
  "Forte",
  "\"Franklin Gothic Book\"",
  "\"Franklin Gothic\"",
  "\"Freestyle Script\"",
  "\"French Script MT\"",
  "Gabriola",
  "Gadugi",
  "Garamond",
  "Georgia",
  "Gigi",
  "\"Gill Sans MT\"",
  "\"Gill Sans\"",
  "\"Global Monospace\"",
  "\"Global Sans Serif\"",
  "\"Global Serif\"",
  "\"Global User Interface\"",
  "\"Gloucester MT\"",
  "\"Goudy Old Style\"",
  "\"Goudy Stout\"",
  "Haettenschweiler",
  "\"Harlow Solid\"",
  "Harrington",
  "\"High Tower Text\"",
  "\"HoloLens MDL2 Assets\"",
  "Impact",
  "\"Imprint MT Shadow\"",
  "\"Informal Roman\"",
  "\"Ink Free\"",
  "\"Javanese Text\"",
  "Jokerman",
  "\"Juice ITC\"",
  "\"Kristen ITC\"",
  "\"Kunstler Script\"",
  "\"Leelawadee UI\"",
  "\"Lucida Bright\"",
  "\"Lucida Calligraphy\"",
  "\"Lucida Console\"",
  "\"Lucida Fax\"",
  "\"Lucida Handwriting\"",
  "\"Lucida Sans Typewriter\"",
  "\"Lucida Sans Unicode\"",
  "\"Lucida Sans\"",
  "Magneto",
  "\"Maiandra GD\"",
  "\"Malgun Gothic\"",
  "Marlett",
  "\"Matura MT Script Capitals\"",
  "\"Microsoft Himalaya\"",
  "\"Microsoft JhengHei UI\"",
  "\"Microsoft JhengHei\"",
  "\"Microsoft New Tai Lue\"",
  "\"Microsoft PhagsPa\"",
  "\"Microsoft Sans Serif\"",
  "\"Microsoft Tai Le\"",
  "\"Microsoft YaHei UI\"",
  "\"Microsoft Yi Baiti\"",
  "MingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "Mistral",
  "\"Modern No. 20\"",
  "\"Mongolian Baiti\"",
  "\"Monotype Corsiva\"",
  "\"MS Gothic\"",
  "\"MS Outlook\"",
  "\"MS PGothic\"",
  "\"MS Reference Sans Serif\"",
  "\"MS Reference Specialty\"",
  "\"MS UI Gothic\"",
  "\"MT Extra\"",
  "\"MV Boli\"",
  "\"Myanmar Text\"",
  "\"Niagara Engraved\"",
  "\"Niagara Solid\"",
  "\"Nirmala UI\"",
  "NumberOnly",
  "\"OCR A\"",
  "\"Old English Text MT\"",
  "Onyx",
  "\"Palace Script MT\"",
  "\"Palatino Linotype\"",
  "Papyrus",
  "Parchment",
  "Perpetua",
  "\"Perpetua Titling MT\"",
  "Playbill",
  "PMingLiU-ExtB",
  "\"Poor Richard\"",
  "Pristina",
  "Rage",
  "Ravie",
  "Rockwell",
  "\"Sans Serif Collection\"",
  "\"Script MT\"",
  "\"Segoe Fluent Icons\"",
  "\"Segoe MDL2 Assets\"",
  "\"Segoe Print\"",
  "\"Segoe Script\"",
  "\"Segoe UI Emoji\"",
  "\"Segoe UI Historic\"",
  "\"Segoe UI Symbol\"",
  "\"Segoe UI Variable Display\"",
  "\"Segoe UI Variable Small\"",
  "\"Segoe UI Variable Text\"",
  "\"Segoe UI\"",
  "\"Showcard Gothic\"",
  "SimSun-ExtB",
  "\"Sitka Banner\"",
  "\"Sitka Display\"",
  "\"Sitka Heading\"",
  "\"Sitka Small\"",
  "\"Sitka Subheading\"",
  "\"Sitka Text\"",
  "\"Snap ITC\"",
  "Stencil",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "\"Tempus Sans ITC\"",
  "\"Times New Roman\"",
  "\"Trebuchet MS\"",
  "\"Tw Cen MT\"",
  "Verdana",
  "\"Viner Hand ITC\"",
  "Vivaldi",
  "\"Vladimir Script\"",
  "Webdings",
  "\"Wide Latin\"",
  "Wingdings",
  "\"Wingdings 2\"",
  "\"Wingdings 3\"",
  "\"Yu Gothic UI\"",
  "\"Yu Gothic\"",
  "仿宋",
  "华文中宋",
  "华文仿宋",
  "华文宋体",
  "华文彩云",
  "华文新魏",
  "华文楷体",
  "华文琥珀",
  "华文细黑",
  "华文行楷",
  "华文隶书",
  "宋体",
  "幼圆",
  "微软雅黑",
  "新宋体",
  "方正姚体",
  "方正舒体",
  "楷体",
  "等线",
  "隶书",
  "黑体"
]

export const COMBINATION_FONTS = [
  '"PingFang SC", 微软雅黑',
  'STSong, 华文中宋',
  '"Kaiti SC", 楷体',
  '"Baoli SC", 隶书',
  '"Songti SC", 宋体',
  'SimSong, 新宋体',
  '"Yuanti SC", 幼圆',
  '"Yuppy SC", 方正姚体',
  // FZShutiAndHanziPenSC = '"HanziPen SC", 方正舒体',
  'STHeiti, 黑体',
  '"Libian SC", 华文新魏',
  'Arial, 等线',
  '"Lantinghei SC", 华文细黑',
  'STKaiti, 华文楷体',
]
